import { createApp } from 'vue'
import App from './App.vue'
import './styles/app.css'
import './styles/legacy/styles.css'
import './styles/legacy/login.css'
import './styles/legacy/cliente-dashboard.css'
import './styles/legacy/servicios-estilos.css'
import './styles/legacy/carrusel-estilos.css'
import './styles/legacy/clientes.css'
import './styles/legacy/mascotas.css'
import './styles/legacy/citas.css'
import './styles/legacy/servicios.css'
import './styles/legacy/imagenes.css'
import './styles/legacy/reportes.css'

createApp(App).mount('#app')
